### ISSUE TITLE
Repository Comments Feb 13

### ISSUE THREAD

**Issue by germonprez** [hacksmath/GHRiskMetrics#1]
A few comments on your repo: 

1) You have a nice start on your README. I have a pretty good idea what you are doing but I don't know what you are leveraging and what you are contributing to (i.e., ghdata). 
2) There appears to be one contributor

**Comment by khtran1994** [comment]
Currently, I'm trying to develop 2 metrics : license detector by using Fossology and CVE by CII census. I will update when I get it worked

**Comment by hacksmath** [comment]
Thank you for the feedback.

1. We plan to contribute license and vulnerability metrics to the ghdata
project. Currently we are researching sources that we hope to leverage to
obtain these metrics.

2. So far contributions have only been made when we were both together, so
only one of us updated the repo.

Micah
